---
title: "Homework 2 (tm2925)"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
```

##Problem 1

```{r read and tidy data1}
transit_data = read_csv(file = "./data1/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() 
  skimr::skim(transit_data)
```


```{r}
transit_data_select = 
  select(transit_data, line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  gather(route1:route11, key = "route", value = "route_lines") %>% 
  mutate(entry_logical = recode(entry, `YES` = "TRUE", `NO` = "FALSE")) 
```

```{r problem 1 questions}
transit_data_select %>% 
distinct(station_name, line) 
#465 distinct stations
sum(transit_data$ada, na.rm = TRUE)
#468 stations ADA compliant
```

```{r}
#proportion of station entrances / exits without vending allow entrance
transit_data_select %>%   
  filter(vending == "NO") %>% 
  nrow() %>% 
  mean(transit_data_select$entry_logical)

  #taking mean of logical variable gives you proportion of TRUE values.
```

Reformat data so that route number and route name are distinct variables. How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant
```{r data1 reformat}
transit_data_select %>% 
filter(route_lines == "A") %>% 
distinct(station_name, ada = TRUE)
```


# Problem 2

```{r eval=FALSE}
trash_data = readxl::read_excel(path = "./data2/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                                sheet = 1, 
                                range = cell_cols("A:N"),
                                skip = row_number(1)) %>% 
janitor::clean_names()
skimr::skim(trash_data) 

gather(trash_data, "trash_type", value = "trash_quantity", plastic_bottles:sports_balls) 
filter(trash_data, !is.na(dumpster)) %>% 
mutate(as.integer(sports_balls))
```

```{r read in data2_2017}
precip_2017 = readxl::read_excel(path = "./data2/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                                sheet = 3,
                                skip = row_number(1)) %>% 
janitor::clean_names()
filter(precip_2017, !is.na(total)) 
filter(precip_2017, !is.na(month)) %>% 
mutate(year = 2017)

precip_2016 = readxl::read_excel(path = "./data2/HealthyHarborWaterWheelTotals2017-9-26.xlsx",
                                sheet = 4,
                                skip = row_number(1)) %>% 
janitor::clean_names()
filter(precip_2016, !is.na(total)) 
filter(precip_2016, !is.na(month)) %>% 
mutate(year = 2016)

precip_data = left_join(precip_2017, precip_2016, by = "month")
colnames(precip_data)[2] = "2017"
colnames(precip_data)[3] = "2016"
```

#Problem 3

```{r}
library(p8105.datasets)
data(brfss_smart2010) 
brfss_smart2010 = brfss_smart2010 %>% 
  janitor::clean_names() 
```

```{r}
brfss = filter(brfss_smart2010, topic == "Overall Health") %>%  
  
  select(-class, -topic, -question, -sample_size, -confidence_limit_low, -confidence_limit_high, -display_order, -data_value_unit, -data_value_type, -data_value_footnote_symbol, -data_value_footnote, -data_source, -class_id, -topic_id, -location_id, -question_id, -respid, -geo_location) %>% 
  
  spread(response, data_value) %>% 
  janitor::clean_names() %>% 
  mutate(good_response = excellent + very_good)
```










